# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:categories/:title

title: MMT
tagline: Dream. Design. Deliver.
email: jsams@mmt.com
description: > # this means to ignore newlines until "baseurl:"
  MMT is a Media Display Company serving the Out of Home Advertising, Sports & Event venues, and Retail Environments since 1987. MMT is credited with modernizing the way outdoor ad campaigns are branded as well as dramatically elevating the perception of the medium.
# baseurl: "/" # For Development
# baseurl: "https://metromedia-technologies.github.io/" # For Production
baseurl: "/MMT/" # For BuildNServ
# url: "localhost:4000" # the base hostname & protocol for development
url: "http://mmt.com" # the base hostname & protocol for production
twitter_username: sams_joseph
github_username:  sams-joseph

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-babel

autoprefixer:
  browsers:
  - last 4 versions
  - ie > 9

sass:
  sass_dir:          _sass
  style:            :compressed

exclude: [
  'node_modules',
  'gulpfile.babel.js',
  'package.json',
  'Gemfile',
  'Gemfile.lock',
  '.babelrc',
  'webpack.config.js',
  'README.md'
]
